path_to_servo_controller:
  ros__parameters:
    csv_file: '/home/ras/tracer_jaka/outputs/coverage_path.csv'
    ee_frame: 'tool0'
    base_frame: 'world'
    kp_linear: 1.5         # 建议带上小数点，明确是浮点数
    kp_angular: 1.0
    max_linear: 0.6
    max_angular: 0.5
    goal_tol_pos: 0.005
    goal_tol_rot: 0.08
    control_rate: 125.0
