# Default initial positions for jaka_zu5's ros2_control fake system

# initial_positions:
#   joint_1: 0
#   joint_2: 0
#   joint_3: 0
#   joint_4: 0
#   joint_5: 0
#   joint_6: 0


  initial_positions:
    joint_1: 1.5707
    joint_2: 1.309
    joint_3: -1.309
    joint_4: 1.5707
    joint_5: 1.5707
    joint_6: 0.785398